# Import libraries 

In [ ]:
import pandas as pd
import numpy as np
import math
from sklearn.model_selection import train_test_split


# Reading Data

In [ ]:
train_data=pd.read_csv('train.csv')
test_data=pd.read_csv('test.csv')
ytest=pd.read_csv('sample_submission.csv')
test_data

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0     1461          20       RH         80.0    11622   Pave   NaN      Reg   
1     1462          20       RL         81.0    14267   Pave   NaN      IR1   
2     1463          60       RL         74.0    13830   Pave   NaN      IR1   
3     1464          60       RL         78.0     9978   Pave   NaN      IR1   
4     1465         120       RL         43.0     5005   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1454  2915         160       RM         21.0     1936   Pave   NaN      Reg   
1455  2916         160       RM         21.0     1894   Pave   NaN      Reg   
1456  2917          20       RL        160.0    20000   Pave   NaN      Reg   
1457  2918          85       RL         62.0    10441   Pave   NaN      Reg   
1458  2919          60       RL         74.0     9627   Pave   NaN      Reg   

     LandContour Utilities  ... ScreenPorch PoolArea PoolQC  Fence  \
0            Lvl    AllPub  ...         120        0    NaN  MnPrv   
1            Lvl    AllPub  ...           0        0    NaN    NaN   
2            Lvl    AllPub  ...           0        0    NaN  MnPrv   
3            Lvl    AllPub  ...           0        0    NaN    NaN   
4            HLS    AllPub  ...         144        0    NaN    NaN   
...          ...       ...  ...         ...      ...    ...    ...   
1454         Lvl    AllPub  ...           0        0    NaN    NaN   
1455         Lvl    AllPub  ...           0        0    NaN    NaN   
1456         Lvl    AllPub  ...           0        0    NaN    NaN   
1457         Lvl    AllPub  ...           0        0    NaN  MnPrv   
1458         Lvl    AllPub  ...           0        0    NaN    NaN   

     MiscFeature MiscVal MoSold  YrSold  SaleType  SaleCondition  
0            NaN       0      6    2010        WD         Normal  
1           Gar2   12500      6    2010        WD         Normal  
2            NaN       0      3    2010        WD         Normal  
3            NaN       0      6    2010        WD         Normal  
4            NaN       0      1    2010        WD         Normal  
...          ...     ...    ...     ...       ...            ...  
1454         NaN       0      6    2006        WD         Normal  
1455         NaN       0      4    2006        WD        Abnorml  
1456         NaN       0      9    2006        WD        Abnorml  
1457        Shed     700      7    2006        WD         Normal  
1458         NaN       0     11    2006        WD         Normal  

[1459 rows x 80 columns]

In [ ]:
test_data=pd.concat([test_data,ytest['SalePrice']],axis=1)
test_data

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0     1461          20       RH         80.0    11622   Pave   NaN      Reg   
1     1462          20       RL         81.0    14267   Pave   NaN      IR1   
2     1463          60       RL         74.0    13830   Pave   NaN      IR1   
3     1464          60       RL         78.0     9978   Pave   NaN      IR1   
4     1465         120       RL         43.0     5005   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1454  2915         160       RM         21.0     1936   Pave   NaN      Reg   
1455  2916         160       RM         21.0     1894   Pave   NaN      Reg   
1456  2917          20       RL        160.0    20000   Pave   NaN      Reg   
1457  2918          85       RL         62.0    10441   Pave   NaN      Reg   
1458  2919          60       RL         74.0     9627   Pave   NaN      Reg   

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0            Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
1            Lvl    AllPub  ...        0    NaN    NaN        Gar2   12500   
2            Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
3            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
4            HLS    AllPub  ...        0    NaN    NaN         NaN       0   
...          ...       ...  ...      ...    ...    ...         ...     ...   
1454         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1455         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1456         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1457         Lvl    AllPub  ...        0    NaN  MnPrv        Shed     700   
1458         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   

     MoSold YrSold  SaleType  SaleCondition      SalePrice  
0         6   2010        WD         Normal  169277.052498  
1         6   2010        WD         Normal  187758.393989  
2         3   2010        WD         Normal  183583.683570  
3         6   2010        WD         Normal  179317.477511  
4         1   2010        WD         Normal  150730.079977  
...     ...    ...       ...            ...            ...  
1454      6   2006        WD         Normal  167081.220949  
1455      4   2006        WD        Abnorml  164788.778231  
1456      9   2006        WD        Abnorml  219222.423400  
1457      7   2006        WD         Normal  184924.279659  
1458     11   2006        WD         Normal  187741.866657  

[1459 rows x 81 columns]

In [ ]:
data =pd.concat([train_data, test_data],axis=0)
data["LandContour"]

0       Lvl
1       Lvl
2       Lvl
3       Lvl
4       Lvl
       ... 
1454    Lvl
1455    Lvl
1456    Lvl
1457    Lvl
1458    Lvl
Name: LandContour, Length: 2919, dtype: object

# Data cleaning & preprocessing 


In [ ]:
data.corr()['SalePrice'].sort_values(ascending=False)

SalePrice        1.000000
GrLivArea        0.588010
OverallQual      0.550911
TotRmsAbvGrd     0.469800
GarageCars       0.469249
GarageArea       0.464809
1stFlrSF         0.462865
TotalBsmtSF      0.453224
FullBath         0.433710
YearBuilt        0.362066
MasVnrArea       0.355608
Fireplaces       0.353567
YearRemodAdd     0.350032
GarageYrBlt      0.325297
LotFrontage      0.318084
LotArea          0.296497
BsmtFinSF1       0.272202
2ndFlrSF         0.272140
WoodDeckSF       0.238381
OpenPorchSF      0.236376
BedroomAbvGr     0.229611
HalfBath         0.228837
BsmtUnfSF        0.175195
BsmtFullBath     0.148210
ScreenPorch      0.082308
PoolArea         0.081039
MoSold           0.067222
3SsnPorch        0.029979
MiscVal         -0.000037
BsmtFinSF2      -0.007437
Id              -0.011630
BsmtHalfBath    -0.012623
LowQualFinSF    -0.015395
YrSold          -0.039064
OverallCond     -0.065785
EnclosedPorch   -0.070698
KitchenAbvGr    -0.071760
MSSubClass      -0.087910
Name: SalePr

In [ ]:
data.describe()

Id   MSSubClass  LotFrontage        LotArea  OverallQual  \
count  2919.000000  2919.000000  2433.000000    2919.000000  2919.000000   
mean   1460.000000    57.137718    69.305795   10168.114080     6.089072   
std     842.787043    42.517628    23.344905    7886.996359     1.409947   
min       1.000000    20.000000    21.000000    1300.000000     1.000000   
25%     730.500000    20.000000    59.000000    7478.000000     5.000000   
50%    1460.000000    50.000000    68.000000    9453.000000     6.000000   
75%    2189.500000    70.000000    80.000000   11570.000000     7.000000   
max    2919.000000   190.000000   313.000000  215245.000000    10.000000   

       OverallCond    YearBuilt  YearRemodAdd   MasVnrArea   BsmtFinSF1  ...  \
count  2919.000000  2919.000000   2919.000000  2896.000000  2918.000000  ...   
mean      5.564577  1971.312778   1984.264474   102.201312   441.423235  ...   
std       1.113131    30.291442     20.894344   179.334253   455.610826  ...   
min       1.000000  1872.000000   1950.000000     0.000000     0.000000  ...   
25%       5.000000  1953.500000   1965.000000     0.000000     0.000000  ...   
50%       5.000000  1973.000000   1993.000000     0.000000   368.500000  ...   
75%       6.000000  2001.000000   2004.000000   164.000000   733.000000  ...   
max       9.000000  2010.000000   2010.000000  1600.000000  5644.000000  ...   

        WoodDeckSF  OpenPorchSF  EnclosedPorch    3SsnPorch  ScreenPorch  \
count  2919.000000  2919.000000    2919.000000  2919.000000  2919.000000   
mean     93.709832    47.486811      23.098321     2.602261    16.062350   
std     126.526589    67.575493      64.244246    25.188169    56.184365   
min       0.000000     0.000000       0.000000     0.000000     0.000000   
25%       0.000000     0.000000       0.000000     0.000000     0.000000   
50%       0.000000    26.000000       0.000000     0.000000     0.000000   
75%     168.000000    70.000000       0.000000     0.000000     0.000000   
max    1424.000000   742.000000    1012.000000   508.000000   576.000000   

          PoolArea       MiscVal       MoSold       YrSold      SalePrice  
count  2919.000000   2919.000000  2919.000000  2919.000000    2919.000000  
mean      2.251799     50.825968     6.213087  2007.792737  180052.854647  
std      35.663946    567.402211     2.714762     1.314964   57381.565721  
min       0.000000      0.000000     1.000000  2006.000000   34900.000000  
25%       0.000000      0.000000     4.000000  2007.000000  154795.084126  
50%       0.000000      0.000000     6.000000  2008.000000  176734.841494  
75%       0.000000      0.000000     8.000000  2009.000000  191895.744157  
max     800.000000  17000.000000    12.000000  2010.000000  755000.000000  

[8 rows x 38 columns]

In [ ]:
data=data.drop(['BsmtFinType1', 'BsmtFinSF1','BsmtFinType2','BsmtFinSF2','BsmtUnfSF','TotalBsmtSF','MasVnrType',
        'MasVnrArea','ExterQual','ExterCond','BsmtFullBath','BsmtHalfBath','PoolArea','PoolQC','Fence','MiscFeature',
          'MiscVal','SaleType','MSZoning','Street','Alley','LotShape','Condition2','LandSlope','GarageCars',
                'GarageQual','GarageCond','PavedDrive','Condition2','Condition1'], axis=1)
data

Id  MSSubClass  LotFrontage  LotArea LandContour Utilities LotConfig  \
0        1          60         65.0     8450         Lvl    AllPub    Inside   
1        2          20         80.0     9600         Lvl    AllPub       FR2   
2        3          60         68.0    11250         Lvl    AllPub    Inside   
3        4          70         60.0     9550         Lvl    AllPub    Corner   
4        5          60         84.0    14260         Lvl    AllPub       FR2   
...    ...         ...          ...      ...         ...       ...       ...   
1454  2915         160         21.0     1936         Lvl    AllPub    Inside   
1455  2916         160         21.0     1894         Lvl    AllPub    Inside   
1456  2917          20        160.0    20000         Lvl    AllPub    Inside   
1457  2918          85         62.0    10441         Lvl    AllPub    Inside   
1458  2919          60         74.0     9627         Lvl    AllPub    Inside   

     Neighborhood BldgType HouseStyle  ...  GarageArea  WoodDeckSF  \
0         CollgCr     1Fam     2Story  ...       548.0           0   
1         Veenker     1Fam     1Story  ...       460.0         298   
2         CollgCr     1Fam     2Story  ...       608.0           0   
3         Crawfor     1Fam     2Story  ...       642.0           0   
4         NoRidge     1Fam     2Story  ...       836.0         192   
...           ...      ...        ...  ...         ...         ...   
1454      MeadowV    Twnhs     2Story  ...         0.0           0   
1455      MeadowV   TwnhsE     2Story  ...       286.0           0   
1456      Mitchel     1Fam     1Story  ...       576.0         474   
1457      Mitchel     1Fam     SFoyer  ...         0.0          80   
1458      Mitchel     1Fam     2Story  ...       650.0         190   

      OpenPorchSF  EnclosedPorch 3SsnPorch ScreenPorch MoSold YrSold  \
0              61              0         0           0      2   2008   
1               0              0         0           0      5   2007   
2              42              0         0           0      9   2008   
3              35            272         0           0      2   2006   
4              84              0         0           0     12   2008   
...           ...            ...       ...         ...    ...    ...   
1454            0              0         0           0      6   2006   
1455           24              0         0           0      4   2006   
1456            0              0         0           0      9   2006   
1457           32              0         0           0      7   2006   
1458           48              0         0           0     11   2006   

     SaleCondition      SalePrice  
0           Normal  208500.000000  
1           Normal  181500.000000  
2           Normal  223500.000000  
3          Abnorml  140000.000000  
4           Normal  250000.000000  
...            ...            ...  
1454        Normal  167081.220949  
1455       Abnorml  164788.778231  
1456       Abnorml  219222.423400  
1457        Normal  184924.279659  
1458        Normal  187741.866657  

[2919 rows x 52 columns]

In [ ]:
from sklearn import preprocessing
object_data=data.select_dtypes(include =['object'])
le=preprocessing.LabelEncoder()
for i in range (object_data.shape[1]):
     object_data.iloc[:,i]=le.fit_transform(object_data.iloc[:,i])
     non_obj_data=data.select_dtypes(exclude =['object'])
     data=pd.concat([object_data,non_obj_data],axis=1)


C:\Users\Win7\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexing.py:1951: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[selected_item_labels] = value
C:\Users\Win7\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\indexing.py:1773: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)


In [ ]:
data=data.dropna()
data

LandContour  Utilities  LotConfig  Neighborhood  BldgType  HouseStyle  \
0               3          0          4             5         0           5   
1               3          0          2            24         0           2   
2               3          0          4             5         0           5   
3               3          0          0             6         0           5   
4               3          0          2            15         0           5   
...           ...        ...        ...           ...       ...         ...   
1451            3          0          4            11         0           2   
1452            3          0          4            10         3           5   
1455            3          0          4            10         4           5   
1456            3          0          4            11         0           2   
1458            3          0          4            11         0           5   

      RoofStyle  RoofMatl  Exterior1st  Exterior2nd  ...  GarageYrBlt  \
0             1         1           12           13  ...       2003.0   
1             1         1            8            8  ...       1976.0   
2             1         1           12           13  ...       2001.0   
3             1         1           13           15  ...       1998.0   
4             1         1           12           13  ...       2000.0   
...         ...       ...          ...          ...  ...          ...   
1451          1         1            9           10  ...       1969.0   
1452          1         1            5            5  ...       1970.0   
1455          1         1            5            5  ...       1970.0   
1456          1         1           12           13  ...       1960.0   
1458          1         1            6            6  ...       1993.0   

      GarageArea  WoodDeckSF  OpenPorchSF  EnclosedPorch  3SsnPorch  \
0          548.0           0           61              0          0   
1          460.0         298            0              0          0   
2          608.0           0           42              0          0   
3          642.0           0           35            272          0   
4          836.0         192           84              0          0   
...          ...         ...          ...            ...        ...   
1451       336.0         160            0              0          0   
1452       286.0           0            0              0          0   
1455       286.0           0           24              0          0   
1456       576.0         474            0              0          0   
1458       650.0         190           48              0          0   

      ScreenPorch  MoSold  YrSold      SalePrice  
0               0       2    2008  208500.000000  
1               0       5    2007  181500.000000  
2               0       9    2008  223500.000000  
3               0       2    2006  140000.000000  
4               0      12    2008  250000.000000  
...           ...     ...     ...            ...  
1451            0       5    2006  188506.431412  
1452            0      12    2006  172917.456816  
1455            0       4    2006  164788.778231  
1456            0       9    2006  219222.423400  
1458            0      11    2006  187741.866657  

[2285 rows x 328 columns]

In [ ]:
data.isnull().sum()

LandContour     0
Utilities       0
LotConfig       0
Neighborhood    0
BldgType        0
               ..
3SsnPorch       0
ScreenPorch     0
MoSold          0
YrSold          0
SalePrice       0
Length: 328, dtype: int64

In [ ]:
data.shape

(2285, 328)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2285 entries, 0 to 1458
Columns: 328 entries, LandContour to SalePrice
dtypes: float64(4), int32(300), int64(24)
memory usage: 3.1 MB


In [ ]:
x = data.drop('SalePrice', axis=1)
y = data[['SalePrice']]   

In [ ]:
from sklearn.preprocessing import StandardScaler
s = StandardScaler()
xs= s.fit_transform(x)
train_x=pd.DataFrame(xs)
train_x


0         1         2         3         4         5         6    \
0     0.315148 -0.020924  0.543572 -1.270596 -0.413338  1.068463 -0.500384   
1     0.315148 -0.020924 -0.736245  1.909740 -0.413338 -0.513121 -0.500384   
2     0.315148 -0.020924  0.543572 -1.270596 -0.413338  1.068463 -0.500384   
3     0.315148 -0.020924 -2.016061 -1.103210 -0.413338  1.068463 -0.500384   
4     0.315148 -0.020924 -0.736245  0.403265 -0.413338  1.068463 -0.500384   
...        ...       ...       ...       ...       ...       ...       ...   
2280  0.315148 -0.020924  0.543572 -0.266279 -0.413338 -0.513121 -0.500384   
2281  0.315148 -0.020924  0.543572 -0.433666  2.039848  1.068463 -0.500384   
2282  0.315148 -0.020924  0.543572 -0.433666  2.857576  1.068463 -0.500384   
2283  0.315148 -0.020924  0.543572 -0.266279 -0.413338 -0.513121 -0.500384   
2284  0.315148 -0.020924  0.543572 -0.266279 -0.413338  1.068463 -0.500384   

          7         8         9    ...       317       318       319  \
0    -0.09878  0.731125  0.736711  ... -0.928431  0.940114  0.251354   
1    -0.09878 -0.524745 -0.668217  ...  0.640700 -0.073116 -0.202372   
2    -0.09878  0.731125  0.736711  ...  0.640700  0.865060  0.560713   
3    -0.09878  1.045093  1.298682  ...  0.640700  0.752479  0.736016   
4    -0.09878  0.731125  0.736711  ...  0.640700  0.827533  1.736276   
...       ...       ...       ...  ...       ...       ...       ...   
2280 -0.09878 -0.210777 -0.106246  ...  0.640700 -0.335805 -0.841713   
2281 -0.09878 -1.466648 -1.511174  ... -0.928431 -0.298278 -1.099511   
2282 -0.09878 -1.466648 -1.511174  ... -0.928431 -0.298278 -1.099511   
2283 -0.09878  0.731125  0.736711  ...  0.640700 -0.673549  0.395722   
2284 -0.09878 -1.152680 -1.230188  ...  0.640700  0.564844  0.777264   

           320       321      322       323      324       325       326  
0    -0.753146  0.200636 -0.35530 -0.099492 -0.29423 -1.558192  0.165983  
1     1.683563 -0.714529 -0.35530 -0.099492 -0.29423 -0.455993 -0.591045  
2    -0.753146 -0.084416 -0.35530 -0.099492 -0.29423  1.013605  0.165983  
3    -0.753146 -0.189435  3.89831 -0.099492 -0.29423 -1.558192 -1.348072  
4     0.816814  0.545698 -0.35530 -0.099492 -0.29423  2.115803  0.165983  
...        ...       ...      ...       ...      ...       ...       ...  
2280  0.555154 -0.714529 -0.35530 -0.099492 -0.29423 -0.455993 -1.348072  
2281 -0.753146 -0.714529 -0.35530 -0.099492 -0.29423  2.115803 -1.348072  
2282 -0.753146 -0.354464 -0.35530 -0.099492 -0.29423 -0.823393 -1.348072  
2283  3.122693 -0.714529 -0.35530 -0.099492 -0.29423  1.013605 -1.348072  
2284  0.800461  0.005601 -0.35530 -0.099492 -0.29423  1.748404 -1.348072  

[2285 rows x 327 columns]

# Spliting data 

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.35, random_state = 1, shuffle = True)

# Models

### 1-Random Forest

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_regression
x, y = make_regression(n_features=80, n_informative=2,random_state=0, shuffle=False)
model1 = RandomForestRegressor(max_depth=10, random_state=0)
model1.fit(x_train, y_train)
model1
predict_x=model1.predict(x_test)
predict_x

C:\Users\Win7\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """


array([145015.12525178, 155936.06396592, 178433.40115428, 205048.00522014,
       189175.56556566, 120520.03101768, 206223.95274557, 166641.55648127,
       161628.70139736, 178801.54836596, 211833.44836004, 139646.46754927,
       155582.1099319 , 158562.0352935 , 379640.12745938, 248427.06140919,
       176696.54408616, 278748.28632434, 190473.92460649, 172392.25219898,
       183776.28944007,  84668.07750262, 152246.60890395, 263436.45986125,
       174970.9812553 , 126675.43721748, 202972.60586979,  95549.6661981 ,
       279867.13956336, 227046.4080988 , 182587.79005375, 192569.88973527,
       177812.19703108, 155138.00945978, 175191.01543944, 165890.69212974,
       193905.41039622, 165898.89771605, 180661.50494908, 193657.59335899,
       231557.16704414, 167270.26237378, 189607.17141012, 146961.0015435 ,
       177709.57786342, 179188.31122945, 158293.69706128, 172897.66785801,
       164456.77261178, 184583.84617279, 197214.60691707, 148560.42390108,
       266235.65494469, 1

In [ ]:
predict_x=model1.predict(x_train)
predict_x

array([128663.07065256, 184850.06120284, 170754.1993197 , ...,
       138686.88390688, 300445.67683717,  93645.98538986])

In [ ]:
print("Train Score ", model1.score(x_train, y_train))
print("Test Score " , model1.score(x_test, y_test))

Train Score  0.9662520439893786
Test Score  0.8623598601513838


### 2-KNN

In [ ]:

from sklearn.neighbors import KNeighborsRegressor
from sklearn import metrics
model2 = KNeighborsRegressor()
model2.fit(x_train, y_train)
predict_x=model2.predict(x_test)
predict_x


array([[203580.        ],
       [192273.47325862],
       [159264.65180982],
       [236378.66516039],
       [181814.27076793],
       [111000.        ],
       [205531.90499087],
       [177149.1975809 ],
       [159631.46706765],
       [158190.6122275 ],
       [224920.        ],
       [145100.        ],
       [164257.89480409],
       [185226.8       ],
       [273860.        ],
       [267700.        ],
       [176189.3397308 ],
       [252975.        ],
       [179769.45904795],
       [157656.92532598],
       [191697.2393609 ],
       [125767.77453115],
       [137988.37779042],
       [294126.4       ],
       [180173.56275002],
       [117710.        ],
       [155371.24580793],
       [ 97180.        ],
       [212700.        ],
       [316486.4       ],
       [186339.68106829],
       [177371.81977247],
       [183772.08465548],
       [146400.        ],
       [144198.55214703],
       [188291.2       ],
       [156179.15504103],
       [164877.89207234],
       [1781

In [ ]:
predict_x=model2.predict(x_train)
predict_x

array([[151265.61282976],
       [185487.53794961],
       [172876.26659793],
       ...,
       [153766.07943167],
       [258374.12617227],
       [123680.92262288]])

In [ ]:
print("Train Score ", model2.score(x_train, y_train))
print("Test Score " , model2.score(x_test, y_test))

Train Score  0.694553527256045
Test Score  0.535872563313353



### 3- Decision tree

In [ ]:
from sklearn.tree import DecisionTreeRegressor
from sklearn import metrics
model3 = DecisionTreeRegressor( max_depth = 3)
model3.fit(x_train, y_train)

predict_x=model3.predict(x_test)
predict_x

array([173162.7346929 , 173162.7346929 , 170992.2275238 , 199865.01494538,
       199865.01494538, 131136.05900621, 189255.23589762, 170992.2275238 ,
       170992.2275238 , 170992.2275238 , 199865.01494538, 131136.05900621,
       170992.2275238 , 173162.7346929 , 295662.34108527, 199865.01494538,
       170992.2275238 , 295662.34108527, 170992.2275238 , 173162.7346929 ,
       173162.7346929 , 131136.05900621, 173162.7346929 , 295662.34108527,
       170992.2275238 , 131136.05900621, 199865.01494538, 131136.05900621,
       295662.34108527, 199865.01494538, 173162.7346929 , 173162.7346929 ,
       170992.2275238 , 131136.05900621, 173162.7346929 , 173162.7346929 ,
       131136.05900621, 170992.2275238 , 170992.2275238 , 173162.7346929 ,
       199865.01494538, 173162.7346929 , 131136.05900621, 131136.05900621,
       189255.23589762, 170992.2275238 , 173162.7346929 , 170992.2275238 ,
       170992.2275238 , 199865.01494538, 199865.01494538, 173162.7346929 ,
       295662.34108527, 1

In [ ]:
predict_x=model3.predict(x_train)
predict_x

array([131136.05900621, 173162.7346929 , 170992.2275238 , ...,
       131136.05900621, 199865.01494538, 131136.05900621])

In [ ]:
print("Train Score ", model3.score(x_train, y_train))
print("Test Score " , model3.score(x_test, y_test))

Train Score  0.6600059196851762
Test Score  0.5987583969821451


### 4- Neural network

In [ ]:
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import confusion_matrix

model4 = MLPRegressor(activation='tanh',  # can be also identity , logistic , relu
                                   solver='lbfgs',  # can be also sgd , adam
                                   learning_rate='constant',  # can be also invscaling , adaptive
                                   early_stopping=False,
                                   alpha=0.0001, hidden_layer_sizes=(100, 3), random_state = 33)

model4.fit(x_train, y_train)
predict_x=model4.predict(x_test)
predict_x


C:\Users\Win7\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1599: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([180218.16247775, 180218.16247775, 180218.16247775, 180218.16247775,
       180218.16247775, 180218.16247775, 180218.16247775, 180218.16247775,
       180218.16247775, 180218.16247775, 180218.16247775, 180218.16247775,
       180218.16247775, 180218.16247775, 180218.16247775, 180218.16247775,
       180218.16247775, 180218.16247775, 180218.16247775, 180218.16247775,
       180218.16247775, 180218.16247775, 180218.16247775, 180218.16247775,
       180218.16247775, 180218.16247775, 180218.16247775, 180218.16247775,
       180218.16247775, 180218.16247775, 180218.16247775, 180218.16247775,
       180218.16247775, 180218.16247775, 180218.16247775, 180218.16247775,
       180218.16247775, 180218.16247775, 180218.16247775, 180218.16247775,
       180218.16247775, 180218.16247775, 180218.16247775, 180218.16247775,
       180218.16247775, 180218.16247775, 180218.16247775, 180218.16247775,
       180218.16247775, 180218.16247775, 180218.16247775, 180218.16247775,
       180218.16247775, 1

In [ ]:
predict_x=model4.predict(x_train)
predict_x

array([180218.16247775, 180218.16247775, 180218.16247775, ...,
       180218.16247775, 180218.16247775, 180218.16247775])

In [ ]:
print("Train Score ", model4.score(x_train, y_train))
print("Test Score " , model4.score(x_test, y_test))

Train Score  -2.432498646953718e-12
Test Score  -0.0062346362341692


### 5- SVM

In [ ]:

from sklearn.svm import SVR
model5 = SVR()
model5.fit(x_train, y_train)

predict_x=model5.predict(x_test)
predict_x


C:\Users\Win7\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([175706.33064069, 175632.07809234, 175592.69555963, 175789.67993708,
       175673.85973117, 175577.73860807, 175784.67109475, 175664.20923982,
       175614.80766219, 175668.14761078, 175726.17608098, 175617.70772428,
       175560.60422628, 175647.98882247, 175752.92219726, 175775.15652176,
       175647.14553351, 175680.69706073, 175738.14812525, 175564.95413179,
       175636.00624188, 175573.62644372, 175563.32359802, 175763.41208213,
       175623.75278842, 175656.7881863 , 175548.05868245, 175517.13175715,
       175672.17215474, 175708.98162093, 175676.62657319, 175531.17310002,
       175638.80945974, 175656.38823067, 175608.97853444, 175635.70004703,
       175598.55728926, 175523.0064483 , 175674.20035377, 175690.2917269 ,
       175717.12735316, 175524.53070128, 175590.21254988, 175616.02125443,
       175646.78163087, 175621.31092279, 175742.02450103, 175576.42988799,
       175596.51730487, 175697.12282184, 175631.20600267, 175525.50056104,
       175700.86851104, 1

In [ ]:
predict_x=model5.predict(x_train)
predict_x

array([175575.16832136, 175746.36499667, 175636.55061817, ...,
       175650.0054658 , 175788.41534809, 175518.71083106])

In [ ]:
print("Train Score ", model5.score(x_train, y_train))
print("Test Score " , model5.score(x_test, y_test))

Train Score  -0.005483837212819198
Test Score  -0.02169423959698258
